### PR TITLE
New encryption algorithm

### PR DESCRIPTION
**Pull request by vokimon**

### CODE REVIEW

**Comment by ecarreras** [comment]
Thank you so much for this great work.

I'll change a few things once merged:

`AUTHORS` file.
@vokimon  What do you prefer your name or SomEnergia or both?

`.tavis.yml` to setup as GISCE-TI

`setup.py` version to bump to 2.0.0 to mark as incompatibility to previous version 0.X - (1.X never released)

**Comment by vokimon** [comment]
Your proposed changes are ok to me.
What about a LICENSE file as well?
Also I had a half way refactor trying to remove the Client class and TestClient by moving the param clamping and formatting inside the encode/decode functions and use them directly. That's why i wrote the parameter metadata (type, lenght...).

**Comment by vokimon** [comment]
Regarding the authors, we could put our names and affiliation. Great part of the development was pair programmed with Aleix, so is fair to credit him as well.

**Comment by vokimon** [comment]
BTW, this PR goes together with the one at webforms repo. Take a look at it as well. It would be nice to have it in production during next week since redsys deadline was November 23th and we are in extension period. The other way would be to put the branch in production, as we did for A3 processes but that would be dirty again.

**Pull request merged**
